Create Indexes for All Products
digitalearthafrica/cube-in-a-box pull request #3
Opened 2021-10-25 08:02 UTC by dominicschaff

All products that provided datasets are now indexed. I have created functions for all the functions, and added them to 2 groups.

The amount of datasets that will be indexed is also customisable by providing the variables INDEX_LIMIT.

2021-10-26 05:08 UTC, alexgleith commented on Makefile
> +INDEX_LIMIT := 10
I think this should be bigger, say, `1,000`.
```suggestion
INDEX_LIMIT := 1000
```

2021-10-26 05:09 UTC, alexgleith requested changes
Love it! One little suggestion.

2021-10-26 07:36 UTC, dominicschaff commented on Makefile
> +INDEX_LIMIT := 10
I shall test the time this takes, and commit

2021-10-26 07:37 UTC, dominicschaff commented
I did also change the default bounding box. So now the bounding box covers south africa

2021-10-26 12:04 UTC, dominicschaff commented on Makefile
> +INDEX_LIMIT := 10
For 10 datasets it takes 5 minutes
For 100 datasets it takes 12 minutes
for 1000 datasets it takes 1.5 hours

2021-10-26 22:14 UTC, alexgleith commented
Hmm, 1.5 hours is too long!

Do you think we can do indexing in parallel instead of sequentially?

2021-10-27 05:07 UTC, dominicschaff commented
> Hmm, 1.5 hours is too long!
> 
> Do you think we can do indexing in parallel instead of sequentially?

I should be able to. I shall investigate

2021-11-22 08:08 UTC, dominicschaff commented
@alexgleith When I ran it now I managed to get it at around 17 minutes.

2021-12-02 01:49 UTC, alexgleith approved these changes

2021-12-02 05:28 UTC, merged